version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - aliyun
  - bilkent
  - braintree
  - cose
  - cytoscape
  - giscus
  - llms
  - llmstxt
  - markline
  - peaceiris
  - teek
  - vitepress-theme-teek
ignoreWords: []
import: []
